### ISSUE TITLE
Index out of bounds when pressing key

### ISSUE THREAD

**Issue by MakerTim** [Direwolf20-MC/BuildingGadgets#103]
Changed the hotkey for switch mode to '\\'
and when i pressed it in Stoneblock (mod manually added) then i crashed with this error message

java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:540)
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
	at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
	at com.direwolf20.buildinggadgets.gui.ModeRadialMenu.isKeyDown(ModeRadialMenu.java:255)
	at com.direwolf20.buildinggadgets.gui.ModeRadialMenu.func_73876_c(ModeRadialMenu.java:235)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1778)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

full crashreport:
https://pastebin.com/BKWRCGRx

**Comment by MakerTim** [comment]
After restart from the modpack
it doesn't crash when having it at the default `G`

so something to do with the key '\\' has to do with it

**Comment by Direwolf20-MC** [comment]
Weird!

**Comment by MakerTim** [comment]
![image](https://user-images.githubusercontent.com/1375359/46605352-81507000-caf9-11e8-897a-364d37ad63f4.png)
that key, no clue if you even have this key 🤔, can test beta if needed

**Comment by MajorTuvok** [comment]
Do you have the exception Message?
(The ordinary Minecraft crash report discards exception Messages for a reasons I don't get...)
(You should be able to find it in the latest.log)
(It might be interesting to see, cause in case of IndexOutOfBoundsException's it usually tells you the index in the message string)

**Comment by MajorTuvok** [comment]
In addition, this might very well be a forge/MC issue (propably mc) - I can see nothing wrong with that code...

**Comment by MakerTim** [comment]
![image](https://user-images.githubusercontent.com/1375359/46631928-30686800-cb49-11e8-8d94-b5ddaa0a98ea.png)
not the index given
