### ISSUE TITLE
[Bug] Undo causes crash, if a block is replaced manually

### ISSUE THREAD

**Issue by DrakeOfTheWest** [Direwolf20-MC/BuildingGadgets#165]
Hi Dire,

love your mod :)

I was building a roof with the building gadget and used it with the undo function to create temporary scaffolding. By accident I build a block of cobble in a place where I intended a framed block to be (not copy-able). So I broke the cobble with a pick and placed the framed block. When I hit the undo button to remove the remaining blocks I got a game crash with the following stack:

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at com.direwolf20.buildinggadgets.common.entities.BlockBuildEntityRender.doRender(BlockBuildEntityRender.java:69)
	at com.direwolf20.buildinggadgets.common.entities.BlockBuildEntityRender.func_76986_a(BlockBuildEntityRender.java:21)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384)
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368)
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I am using the version from the latest Enigmatica 2 pack

A rare case, but hopefully not too hard to fix :)

Kind regards

**Comment by MichaelHillcox** [comment]
Well than that looks like fun, could you do a full crashlog on pastebin and link at please :) As for the crash, I'll see what I can do to reproduce it.

**Comment by MichaelHillcox** [comment]
So I've just tried to do this on my end and I can't seem to do it. Were you using the building gadget or the copy and paste gadget?

**Comment by MichaelHillcox** [comment]
I've created a PR to hopefully resolve this. Sorry to ask due to the load times but would you be able to test this build of the mod? 

Can you try to reproduce the issue. If the issue is resolved then hopefully we can push out an official fix pretty soon :)

https://drive.google.com/open?id=15O2Inux9IU2ruHkaxPRGZ3T1n33gdklq

**Comment by DrakeOfTheWest** [comment]
Will do. I won't have time for it today, but probably tomorrow

**Comment by MichaelHillcox** [comment]
@DrakeOfTheWest any updates?

**Comment by DrakeOfTheWest** [comment]
It worked. Good job and thank you :)

**Comment by MichaelHillcox** [comment]
I'll update my PR thanks for confirming!
