### ISSUE TITLE
um... rly? (crash)

### ISSUE THREAD

**Issue by DevTimur** [Direwolf20-MC/BuildingGadgets#192]
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at com.direwolf20.buildinggadgets.gui.DestructionGUI.sizeCheckBoxes(DestructionGUI.java:150)
	at com.direwolf20.buildinggadgets.gui.DestructionGUI.func_146284_a(DestructionGUI.java:165)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at com.direwolf20.buildinggadgets.gui.DestructionGUI.func_73864_a(DestructionGUI.java:237)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at com.direwolf20.buildinggadgets.gui.DestructionGUI.func_146274_d(DestructionGUI.java:250)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1758)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
	at org.multimc.EntryPoint.listen(EntryPoint.java:170)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

**Comment by DevTimur** [comment]
Easy to replicate, just make one of input fields in Destruction gadget empty (not 0)

**Comment by Phylogeny** [comment]
1. Please change the title to something more descriptive.
2. Please edit your post by replacing that portion of the crash report with a link to the full report.

**Comment by Phylogeny** [comment]
For anyone interested, there is no parsing performed at line 150 in the latest release (v2.5.0): https://github.com/Direwolf20-MC/BuildingGadgets/blob/8eb69538a10269f7eccdd9411548e0045f1a149b/src/main/java/com/direwolf20/buildinggadgets/client/gui/DestructionGUI.java#L150-L152
This crash must be from v2.4.6 or earlier.

**Comment by Phylogeny** [comment]
@DevTimur For archival purposes, can you still change the title to a proper description of the crash?

**Comment by Phylogeny** [comment]
Ok, I did it for you...

**Comment by Phylogeny** [comment]
Duplicate of #193
