### ISSUE TITLE
1.14.4 current version requires an older Forge version

### ISSUE THREAD

**Issue by RepoDraghon** [Direwolf20-MC/BuildingGadgets#337]
Just bringing this to your attention, not saying anything has to be done right away but there are mods I use in 1.14.4 that require the latest forge and because 1 I don't know what version this mod is stalled on for Forge but 2 I reiterate that other mods have moved on preventing this to be compatible... I cannot use this mod...

**Comment by raziel23x** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 8/3/19 10:23 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at com.direwolf20.buildinggadgets.common.registry.objects.BuildingObjects.initColorHandlers(BuildingObjects.java:33) ~[?:3.0.0] {}
	at com.direwolf20.buildinggadgets.common.BuildingGadgets$$Lambda$2912/1594238395.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2026/1438120433.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-0.10.6-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163) ~[?:28.0] {}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$28(ModLoader.java:238) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader$$Lambda$3524/2062211033.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:209) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:238) ~[?:?] {}
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:196) ~[?:?] {}
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:501) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?] {pl:accesstransformer:B,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.0.37.jar:28.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$345/1510731556.call(Unknown Source) [forge-1.14.4-28.0.37.jar:28.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.1.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.direwolf20.buildinggadgets.common.registry.objects.BuildingObjects.initColorHandlers(BuildingObjects.java:33)
	at com.direwolf20.buildinggadgets.common.BuildingGadgets$$Lambda$2912/1594238395.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2026/1438120433.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:163)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$28(ModLoader.java:238)
	at net.minecraftforge.fml.ModLoader$$Lambda$3524/2062211033.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:209)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:238)
	at net.minecraftforge.client.ForgeHooksClient.onBlockColorsInit(ForgeHooksClient.java:196)
	at net.minecraft.client.renderer.color.BlockColors.func_186723_a(BlockColors.java:76)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:501)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$345/1510731556.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 329211288 bytes (313 MB) / 4029153280 bytes (3842 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.1.1+59+e32e753
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-0.10.6-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.0.37.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.37.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-0.16.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.0.37.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.0.37.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.0.37.jar fml TRANSFORMATIONSERVICE 
	FML: 28.0
	Forge: net.minecraftforge:28.0.37
	FML Language Providers: 
		javafml@28.0
		kotori_scala@2.12.8
	Mod List: 
		A+Block+of+Charcoal-1.2.jar A Block of Charcoal {charcoalblock@1.2 LOAD_REGISTRIES}
		angelblock-1.0.jar Angel Block {angelblock@1.0 LOAD_REGISTRIES}
		angelring-1.14.4-1.0.0.jar Angel Ring {angelring@1.0.0 LOAD_REGISTRIES}
		Apotheosis-1.14.4-2.1.0.jar Apotheosis {apotheosis@2.1.0 LOAD_REGISTRIES}
		AppleSkin-mc1.14.3-forge-1.0.11.jar AppleSkin {appleskin@1.0.11 LOAD_REGISTRIES}
		AttributeFix-1.14.4-3.0.1.jar AttributeFix {attributefix@3.0.1 LOAD_REGISTRIES}
		bambooeverything-1.14-1.2.0.jar Bamboo Everything {bambooeverything@1.14-1.2.0 LOAD_REGISTRIES}
		betteranimalsplus-1.14.4-7.0.1.jar Better Animals Plus {betteranimalsplus@7.0.1 LOAD_REGISTRIES}
		BetterCrates-1.14.4-1.0.0.jar Better Crates {bettercrates@1.0.0 LOAD_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.197-universal.jar Biomes O' Plenty {biomesoplenty@version LOAD_REGISTRIES}
		branders-enhanced-mob-spawners.v1.4.1-1.14.4.jar Enhanced Mob Spawners {spawnermod@1.4.1 LOAD_REGISTRIES}
		buildinggadgets-3.0.0.jar Building Gadgets {buildinggadgets@version LOAD_REGISTRIES}
		bwncr-1.14.4-3.5.10.jar Bad Wither No Cookie Reloaded {bwncr@1.14.4-3.5.10 LOAD_REGISTRIES}
		caelus-FORGE-1.14.4-0.10.jar Caelus API {caelus@FORGE-1.14.4-0.10 LOAD_REGISTRIES}
		campfiretorches-1.14.4-1.0.0.jar Campfire Torches {campfiretorches@1.14.4-1.0.0 LOAD_REGISTRIES}
		ceilingtorch-1.14.4-v1.2.jar Ceiling Torch {ceilingtorch@v1.2 LOAD_REGISTRIES}
		ChineseWorkshop-1.14.4-2.3.0.jar ChineseWorkshop {chineseworkshop@2.3.0 LOAD_REGISTRIES}
		ChunkNoGoByeBye-1.14.4-1.0.2.jar ChunkNoGoByeBye {chunknogobyebye@1.14.4-1.0.2 LOAD_REGISTRIES}
		compressed_items-1.14.4-1.0.jar Compressed Items {compressed_items@1.14.4-1.0 LOAD_REGISTRIES}
		Controlling-5.0.3.jar Controlling {controlling@5.0.3 LOAD_REGISTRIES}
		corail_woodcutter-1.0.3-1.14.4.jar Corail Woodcutter {corail_woodcutter@1.0.3 LOAD_REGISTRIES}
		CosmeticArmorReworked-1.14.4-v1.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1 LOAD_REGISTRIES}
		craftingstation-2.0.0.jar Crafting Station {craftingstation@2.0.0 LOAD_REGISTRIES}
		Cucumber-1.14.4-2.0.1.jar Cucumber Library {cucumber@2.0.1 LOAD_REGISTRIES}
		curios-FORGE-1.14.4-0.20.jar Curios API {curios@FORGE-1.14.4-0.20 LOAD_REGISTRIES}
		curiouselytra-FORGE-1.14.4-0.7.jar Curious Elytra {curiouselytra@FORGE-1.14.4-0.7 LOAD_REGISTRIES}
		curiousshulkerboxes-FORGE-1.14.4-0.8.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.14.4-0.8 LOAD_REGISTRIES}
		DefaultSettings-1.14.4-1.3.2.jar DefaultSettings {defaultsettings@1.3.2 LOAD_REGISTRIES}
		ElementaryOres-1.14.4-0.0.1.jar Elementary Ores {elementaryores@1.14.4-0.0.1 LOAD_REGISTRIES}
		ElevatorMod-1.14.4-1.3.11.jar Elevator Mod {elevatorid@1.14.4-1.3.11 LOAD_REGISTRIES}
		EnchantmentDescriptions-1.14.4-1.3.3.jar EnchantmentDescriptions {enchdesc@1.3.3 LOAD_REGISTRIES}
		ender_compass-2.2.1.jar Ender Compass {ender_compass@2.2.1 LOAD_REGISTRIES}
		EnderBags-1.14.4-4.1.0.jar Ender Bags {ender_bags@4.1.0 LOAD_REGISTRIES}
		EnderMagnet-1.14.3-1.0.0.jar Ender Magnet {endermagnet@1.14.3-1.0.0 LOAD_REGISTRIES}
		endteleporters-1.1.0-1.14.4.jar End Teleporters {endteleporters@1.1.0 LOAD_REGISTRIES}
		essentials-1.14.4-2.3.1.jar Essentials {essentials@1.14.4-2.3.1 LOAD_REGISTRIES}
		extdiamond-1.0.jar Extended diamond {extdiamond@1.0 LOAD_REGISTRIES}
		f2l-0.1.8_forge.jar Flesh 2 Leather {f2l@0.1.8_forge LOAD_REGISTRIES}
		FastLeafDecay-v16.jar FastLeafDecay {fastleafdecay@v16 LOAD_REGISTRIES}
		Fence Jumper-1.14.4-1.0.8.jar FenceJumper {fencejumper@version LOAD_REGISTRIES}
		firstaid-1.7.6.jar First Aid {firstaid@1.7.6 LOAD_REGISTRIES}
		fishtraps-0.0.4.jar Fish Traps {fishtraps@1.14.4-0.0.4 LOAD_REGISTRIES}
		FleshToLeather-1.14.3-1.1.0.jar FleshToLeather {fleshtoleather@1.1.0 LOAD_REGISTRIES}
		forbidden_arcanus-1.14.4-1.0-Beta-2.jar Forbidden & Arcanus {forbidden_arcanus@1.14.4-1.0-Beta-2 LOAD_REGISTRIES}
		forgemod_VoxelMap-1.9.13_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 LOAD_REGISTRIES}
		FpsReducer-mc1.14.4-1.12.4.jar FPS Reducer {fpsreducer@mc1.14.4-1.12.4 LOAD_REGISTRIES}
		FTBUtilitiesBackups-2.0.0.7.jar FTB Utilities: Backups {ftbbackups@2.0.0.7 LOAD_REGISTRIES}
		furniture-7.0.0-pre3-1.14.4.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre3 LOAD_REGISTRIES}
		GemsPlusPlus -1.14.4-0.1.1.jar GemsPlusPlus {gemsplusplus@0.1.0 LOAD_REGISTRIES}
		globaldatapack-1.14.4-1.1.jar Dark Roleplay - Global Datapacks {drpglobaldatapack@1.14.4-1.1 LOAD_REGISTRIES}
		globalxp-1.14.4-v1.4.5.jar Global XP {globalxp@v1.4.5 LOAD_REGISTRIES}
		Gobber2-1.14.4-2.1.74.jar Gobber 2 {gobber2@2.1.74 LOAD_REGISTRIES}
		gravestone-1.15.0.jar Gravestone Mod {gravestone@1.15.0 LOAD_REGISTRIES}
		Hwyla-forge-1.10.4-B65_1.14.2.jar Waila {waila@version LOAD_REGISTRIES}
		Immersive Recipes-1.14.4-1.2.1.jar Immersive Recipes {immersiverecipes@1.2.0 LOAD_REGISTRIES}
		inventorysorter-1.14.4-15.2.0.jar Simple Inventory Sorter {inventorysorter@15.2.0 LOAD_REGISTRIES}
		ironchest-1.14.3-9.0.DEV.55a7af2.jar Iron Chests {ironchest@1.14.3-9.0.DEV.55a7af2 LOAD_REGISTRIES}
		jei-1.14.3-6.0.0.8.jar Just Enough Items {jei@6.0.0.8 LOAD_REGISTRIES}
		Kiwi-1.14.3-2.2.5.jar Kiwi {kiwi@2.2.5 LOAD_REGISTRIES}
		KleeSlabs_1.14.3-7.4.6.jar KleeSlabs {kleeslabs@7.4.6 LOAD_REGISTRIES}
		LargeFluidTank-14.6.6.jar FluidTank {fluidtank@14.6.6 LOAD_REGISTRIES}
		LightOverlay-3.3.1.jar Light Overlay Forge {lightoverlay-forge@3.3.1 LOAD_REGISTRIES}
		lycanitesmobs-1.14.4-2.1.0.0-beta13.jar Lycanites Mobs {lycanitesmobs@1.0 LOAD_REGISTRIES}
		mcjtylib-1.14-3.5.5-alpha.jar McJtyLib {mcjtylib@NONE LOAD_REGISTRIES}
		metalbarrels-1.3b.jar Metal Barrels {metalbarrels@1.3b LOAD_REGISTRIES}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 LOAD_REGISTRIES}
		moreboots-1.1.5.jar More Boots {moreboots@1.1.5 LOAD_REGISTRIES}
		MoreCrashInfo-1.0.2.jar MoreCrashInfo {morecrashinfo@1.0.2 LOAD_REGISTRIES}
		moreprog-1.14.4-0.3.4.jar MoreProgression {moreprogression@0.3.4 LOAD_REGISTRIES}
		Overloaded-1.14.4-0.0.70.jar Overloaded {overloaded@1.14.4-0.0.70 LOAD_REGISTRIES}
		overloadedarmorbar-3.0.0.jar Example Mod {overloadedarmorbar@3.0.0 LOAD_REGISTRIES}
		PickleTweaks-1.14.4-3.0.2.jar Pickle Tweaks {pickletweaks@3.0.2 LOAD_REGISTRIES}
		Placebo-1.14.4-2.1.2.jar Placebo {placebo@2.1.2 LOAD_REGISTRIES}
		Portality-1.14.4-2.0.12.jar Portality {portality@NONE LOAD_REGISTRIES}
		practicaltools-1.14.4-1.3b.jar Practical Tools {practicaltools@1.14.4-1.3b LOAD_REGISTRIES}
		PyramidPlunder-1.14.4-1.0.jar Pyramid Plunder {pyramidplunder@1.14.4-1.0 LOAD_REGISTRIES}
		randompatches-1.14.4-1.17.3.1.jar RandomPatches {randompatches@1.14.4-1.17.3.1 LOAD_REGISTRIES}
		reap-1.10.0.jar Reap Mod {reap@1.10.0 LOAD_REGISTRIES}
		rftoolsbase-1.14-0.0.2-alpha.jar RFToolsBase {rftoolsbase@NONE LOAD_REGISTRIES}
		rftoolspower-1.14-1.2.2-alpha.jar RFToolsPower {rftoolspower@NONE LOAD_REGISTRIES}
		RingOfAttraction-1.14.4-1.0.2.jar Ring of Attraction {ring_of_attraction@1.0.2 LOAD_REGISTRIES}
		RingOfBlink-1.0.6.jar Ring of Blink {ring_of_blink@1.0.6 LOAD_REGISTRIES}
		RingOfEnderchest-1.14.4-1.0.5.jar Ring of Enderchest {ring_of_enderchest@1.0.5 LOAD_REGISTRIES}
		RingOfGrowth-1.14.4-1.0.6.jar Ring of Growth {ring_of_growth@1.0.6 LOAD_REGISTRIES}
		RingOfMiner-1.14.4-1.0.3.jar Ring of Miner {ring_of_miner@1.0.3 LOAD_REGISTRIES}
		RingOfRepair-1.14.4-1.0.5.jar Ring of Repair {ring_of_repair@1.0.5 LOAD_REGISTRIES}
		RingOfTeleport-1.14.4-1.0.5.jar Ring of Teleport {ring_of_teleport@1.0.5 LOAD_REGISTRIES}
		rsgauges-1.14.4-1.1.6-b1.jar Redstone Gauges and Switches {rsgauges@1.1.6-b1 LOAD_REGISTRIES}
		Sauuuuucey's Ores-1.14.4-1.3-release.jar Sauuuuucey's Ores {sauuuuuceysores@1.3-release LOAD_REGISTRIES}
		Sauuuuucey's+Farming-1.14.3-1.0-beta.jar Sauuuuucey's Farming {sauuuuuceysfarming@1.0-beta LOAD_REGISTRIES}
		ServerTabInfo-1.14.4-1.2.5-beta.jar Server Tab Info {servertabinfo@1.2.5-beta LOAD_REGISTRIES}
		SilentGear-1.14.4-1.3.4+53.jar Silent Gear {silentgear@1.3.4+53 LOAD_REGISTRIES}
		SilentGems-1.14.4-3.3.1+56.jar Silent's Gems 3 {silentgems@3.3.1+56 LOAD_REGISTRIES}
		SilentLib-1.14.4-4.3.0+38.jar Silent Lib {silentlib@4.3.0+38 LOAD_REGISTRIES}
		simplefarming-1.14.4-1.0.7.jar Simple Farming {simplefarming@1.14.4-1.0.7 LOAD_REGISTRIES}
		simpleores-1.14.4-2.0.6.0.jar Simple Ores {simpleores@1.14.4-2.0.6.0 LOAD_REGISTRIES}
		SimpleStorageNetwork-1.14.4-0.0.8.jar Simple Storage Network {storagenetwork@1.14.4-0.0.8 LOAD_REGISTRIES}
		simplylight-1.14.4-0.8.5.jar Simply Light {simplylight@1.14.4-0.8.5 LOAD_REGISTRIES}
		StoneChest-1.14.4-1.0.1.jar Stone Chest {stonechest@1.0.1 LOAD_REGISTRIES}
		StoneCraftingTable-1.14.4-1.0.5.jar Stone Crafting Table {sct@1.0.5 LOAD_REGISTRIES}
		SuperTools-1.3.jar Super Tools {supertools@1.3 LOAD_REGISTRIES}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 LOAD_REGISTRIES}
		theoneprobe-1.14-1.4.32-alpha.jar The One Probe {theoneprobe@NONE LOAD_REGISTRIES}
		theplopper-1.14.4-v1.2.2.jar The Plopper {theplopper@v1.2.2 LOAD_REGISTRIES}
		titanium-2.1.53.jar Titanium {titanium@2.1.53 LOAD_REGISTRIES}
		ToastControl-1.14.4-2.1.1.jar Toast Control {toastcontrol@2.1.1 LOAD_REGISTRIES}
		ToolBelt-1.14.4-1.9.10.jar Tool Belt {toolbelt@1.9.10 LOAD_REGISTRIES}
		TorchBandolier-1.14.4-1.3.1+6.jar Torch Bandolier {torchbandolier@1.3.1+6 LOAD_REGISTRIES}
		torchmaster-2.0.0.4-alpha.jar Torchmaster {torchmaster@2.0.0.4-alpha LOAD_REGISTRIES}
		toughnessbar-4.0.jar Toughness Bar {toughnessbar@4.0 LOAD_REGISTRIES}
		u_team_core-1.14.4-2.7.0.129.jar U Team Core {uteamcore@2.7.0.129 LOAD_REGISTRIES}
		undermat-1.14.4-1.0.1.jar Underground Materials {undermat@1.0.0 LOAD_REGISTRIES}
		useful_backpacks-1.14.4-1.7.0.34.jar Useful Backpacks {usefulbackpacks@1.7.0.34 LOAD_REGISTRIES}
		useful_resources-1.14.4-0.10.0.5-SNAPSHOT.jar Useful Resources {usefulresources@0.10.0.5-SNAPSHOT ERROR}
		WaterStrainer-1.14.4-7.0.0.jar Water Strainer {waterstrainer@1.14.4-7.0.0 LOAD_REGISTRIES}
		weapon_craftery-1.14.4-1.0-Beta-2.jar Weapon Craftery {weapon_craftery@1.14.4-1.0-Beta-2 LOAD_REGISTRIES}
		wetstone-1.1.2.jar Wetstone {wetstone@1.1.2 LOAD_REGISTRIES}
		WoolToString-1.14.2-1.0.0.jar WoolToString {wooltostring@1.0.0 LOAD_REGISTRIES}
		wrenchest-1.14.x-v1.0.jar Wrenchest {wrenchest@v1.0 LOAD_REGISTRIES}
		XL-Food-Mod-1.14.4-2.0.3.jar XL Food Mod {xlfoodmod@2.0.3 LOAD_REGISTRIES}
		YAMDA-4.0.0.jar YAMDA {yamda@4.0.0 LOAD_REGISTRIES}
		Upgrade Aquatic Wave Three v2 - Beta v1.0.4.jar Upgrade Aquatic {upgrade_aquatic@1.0.4 LOAD_REGISTRIES}
		forge-1.14.4-28.0.37-universal.jar Forge {forge@28.0.37 LOAD_REGISTRIES}
	Launched Version: forge-28.0.37
	LWJGL: 3.2.2 build 10
	OpenGL: GeForce GTX 980 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 430.86, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, file/Soartex_Fanver.zip
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz

**Comment by RepoDraghon** [comment]
Why didn't you start a new issue?
