### ISSUE TITLE
Building Gadgets 1.14.4 NOT WORKING

### ISSUE THREAD

**Issue by ItzTwoost** [Direwolf20-MC/BuildingGadgets#404]
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/10/19 11:20 AM
Description: Initializing game

java.lang.IllegalStateException: The ObjectHolder annotation cannot apply to a field that does not map to a registry. Ensure the registry was created during the RegistryEvent.NewRegistry event. (found : com.direwolf20.buildinggadgets.api.serialisation.ITemplateSerializer at com.direwolf20.buildinggadgets.api.serialisation.SerialisationSupport.DELEGATING_TEMPLATE_SERIALIZER)
	at net.minecraftforge.registries.ObjectHolderRef.<init>(ObjectHolderRef.java:95) ~[?:?] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:154) ~[?:?] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:111) ~[?:?] {}
	at net.minecraftforge.registries.ObjectHolderRegistry$$Lambda$2440/324998670.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_51] {}
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:111) ~[?:?] {}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:79) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1978/1802493587.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1979/1372802818.run(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:79) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:453) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:155) [?:?] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.14.4-28.1.0.jar:28.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$348/1179689991.call(Unknown Source) [forge-1.14.4-28.1.0.jar:28.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80) [modlauncher-3.2.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-3.2.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ObjectHolderRef.<init>(ObjectHolderRef.java:95)
	at net.minecraftforge.registries.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:154)
	at net.minecraftforge.registries.ObjectHolderRegistry.lambda$findObjectHolders$8(ObjectHolderRegistry.java:111)
	at net.minecraftforge.registries.ObjectHolderRegistry$$Lambda$2440/324998670.accept(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at net.minecraftforge.registries.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:111)
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$begin$2(ClientModLoader.java:79)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1978/1802493587.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.lambda$createRunnableWithCatch$5(ClientModLoader.java:95)
	at net.minecraftforge.fml.client.ClientModLoader$$Lambda$1979/1372802818.run(Unknown Source)
	at net.minecraftforge.fml.client.ClientModLoader.begin(ClientModLoader.java:79)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:453)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:365)
	at net.minecraft.client.main.Main.main(SourceFile:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$348/1179689991.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:50)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:68)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:80)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1367232776 bytes (1303 MB) / 2156920832 bytes (2057 MB) up to 6524764160 bytes (6222 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx7000m -Xms256m -XX:PermSize=256m
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine_1.14.4_HD_U_F4.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		[1.14.4] SecurityCraft v1.8.14.jar SecurityCraft {securitycraft@v1.8.14 CREATE_REGISTRIES}
		AppleSkin-mc1.14.4-forge-1.0.12.jar AppleSkin {appleskin@1.0.12 LOAD_REGISTRIES}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 LOAD_REGISTRIES}
		BetterCaves-1.14.4-1.0.1.jar YUNG's Better Caves {bettercaves@1.14.4-1.0.1 CREATE_REGISTRIES}
		BiomesOPlenty-1.14.4-9.0.0.257-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.256 CREATE_REGISTRIES}
		buildinggadgets-3.0.6a.jar Building Gadgets {buildinggadgets@3.0.6a CREATE_REGISTRIES}
		caelus-FORGE-1.14.4-1.0.1.jar Caelus API {caelus@FORGE-1.14.4-1.0.1 LOAD_REGISTRIES}
		Clumps-4.0.0.jar Clumps {clumps@4.0.0 LOAD_REGISTRIES}
		colytra-FORGE-1.14.4-2.0.jar Colytra {colytra@FORGE-1.14.4-2.0 LOAD_REGISTRIES}
		compressed_items-1.14.4-1.1.jar Compressed Items {compressed_items@1.14.4-1.1 LOAD_REGISTRIES}
		Controlling-5.0.4.jar Controlling {controlling@5.0.4 CREATE_REGISTRIES}
		CosmeticArmorReworked-1.14.4-v1a.jar CosmeticArmorReworked {cosmeticarmorreworked@1.14.4-v1a CREATE_REGISTRIES}
		Cyclic-1.14.4-0.0.12.jar Cyclic {cyclic@1.14.4-0.0.12 LOAD_REGISTRIES}
		DefaultOptions_1.14.4-10.2.6.jar Default Options {defaultoptions@10.2.6 CREATE_REGISTRIES}
		Ding-1.14.4-1.1.0.jar Ding {ding@1.1.0 LOAD_REGISTRIES}
		ec_1.14-1.0.jar Enchanting Commands {ec@1.0 CREATE_REGISTRIES}
		embellishcraft-1.14.4-1.3.1.jar EmbellishCraft {embellishcraft@1.14.4-1.3.1 CREATE_REGISTRIES}
		EnchantmentDescriptions-1.14.4-1.3.8.jar EnchantmentDescriptions {enchdesc@1.3.8 CREATE_REGISTRIES}
		extragolems-9.0.4.jar Extra Golems {golems@9.0.4 CONSTRUCT}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 CREATE_REGISTRIES}
		forgemod_VoxelMap-1.9.13b_for_1.14.4.jar VoxelMap {voxelmap@1.9.13 CREATE_REGISTRIES}
		glassential-forge-1.14.4-1.1.1.jar Glassential {glassential@1.1.1 LOAD_REGISTRIES}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version LOAD_REGISTRIES}
		jei-1.14.4-6.0.0.24.jar Just Enough Items {jei@6.0.0.24 LOAD_REGISTRIES}
		metalbarrels-1.4.jar Metal Barrels {metalbarrels@1.4 LOAD_REGISTRIES}
		modnametooltip_1.14.3-1.12.1.jar Mod Name Tooltip {modnametooltip@1.12.1 LOAD_REGISTRIES}
		Modpack Configuration Checker-1.14.x-v1.7.1.jar Modpack Config Checker {concheckrmd@1.7.1 LOAD_REGISTRIES}
		MouseTweaks-2.12-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.12 LOAD_REGISTRIES}
		mysticallib-1.14.4-1.6.0.jar Mystical Lib {mysticallib@1.14.4-1.6.0 LOAD_REGISTRIES}
		Neat 1.5-19.jar Neat {neat@1.5-19 LOAD_REGISTRIES}
		PrettyBeaches_1.14.4-3.0.7.jar Pretty Beaches {prettybeaches@3.0.7 LOAD_REGISTRIES}
		randomenchants-2.1.0.jar Random Enchants {randomenchants@2.1.0 CONSTRUCT}
		RandomThings-MC1.14.4-5.0.1.jar Random Things {randomthings@5.0.1 LOAD_REGISTRIES}
		Rays Dongles-1.14.4-2.0.4d.jar Ray's Dongles {slurpiesdongles@2.0.4d CREATE_REGISTRIES}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 LOAD_REGISTRIES}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE LOAD_REGISTRIES}
		traverse-1.14.4-2.0.0.jar Traverse {traverse@1.14.4-2.0.0 CREATE_REGISTRIES}
		upsizer-mc1.14.4-5.0b2.jar Upsizer {upsizer@5.0.0b2 LOAD_REGISTRIES}
		VanillaTweaks-1.14.4.1.5.10.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.10 CREATE_REGISTRIES}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 CONSTRUCT}
		Aquaculture-1.14.4-2.0.2.jar Aquaculture 2 {aquaculture@1.14.4-2.0.2 CONSTRUCT}
		forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 CONSTRUCT}
	Launched Version: forge-28.1.0
	LWJGL: 3.2.2 build 10
	OpenGL: Intel(R) HD Graphics 630 GL version 4.5.0 - Build 23.20.16.4973, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: ~~ERROR~~ NullPointerException: null
	CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
	OptiFine Version: OptiFine_1.14.4_HD_U_F4
	OptiFine Build: 20191025-153543
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 4.5.0 - Build 23.20.16.4973
	OpenGlRenderer: Intel(R) HD Graphics 630
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by MajorTuvok** [comment]
Please keep to our issue template... 
- missing mod and forge version
- missing description
Also your bug report is abosluetly unreadable, don't just dump it into the issue - send us a link to a pastebin, gist or similiar site...
Also I'd request that you send us latest.log or debug.log, so we can better see what was happening.

**Comment by MajorTuvok** [comment]
This package (`com.direwolf20.buildinggadgets.api.serialisation.ITemplateSerializer`) no longer exists as of 3.1.1. Update Forge and Buildinggadgets to the latest versions and submit a proper bug report and we can reopen this.

**Comment by ItzTwoost** [comment]
Im new to this and I'm just trying to play minecraft with mods. How do I send a proper debug log?

**Comment by MajorTuvok** [comment]
First of all update your buildinggadgets and forge versions. The stacktrace you gave me clearly shows that you are not running the latest version
