### ISSUE TITLE
Crash when selecting flower from Ferdinand's flowers mod with the builder 

### ISSUE THREAD

**Issue by EBrarian** [Direwolf20-MC/BuildingGadgets#425]
When selecting a flower from the Ferdinand's flowers mod with the builder I get the following crash :

https://pastebin.com/vsBxE4wd

The builder tool must be removed from the players inventory with a tool such as NBTexplorer to get the world to load again, otherwise infinite crash loop.

Not sure if this a building gadgets issue or a Ferdinand's flowers mod issue.

works fine with flowers/plants from other mods like the plants mod or vanilla.

**Comment by MajorTuvok** [comment]
This is a Ferdinands Flower mod issue, as they do not use the blockstate passed in, but instead attempt to retrieve it from the world with checking, that it is actually present.

**Comment by MajorTuvok** [comment]
Without looking at the code, I'm 99% sure that the mod author of Ferdinands Flower mod has made the same error as mcenderdragon in Futurepack or the mod authors of galacticraft before - this is related to #354.

**Comment by MichaelHillcox** [comment]
Yeah, I'm pretty sure I'm in agreement with this. We don't crash on any Minecraft blocks or flowers. Sounds to me like the mod author is doing something funky / wrong

**Comment by Exceptionfault** [comment]
Got another one of those issues with the Exchanger and Biome o' Plenties Silty Dirt Farmland.

`java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.common.block.BlockBOPDirt$BOPDirtType, values=[silty]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at biomesoplenty.common.block.BlockBOPFarmland.getDirtBlockState(BlockBOPFarmland.java:221)
    at biomesoplenty.common.block.BlockBOPFarmland.getPickBlock(BlockBOPFarmland.java:199)
    at com.direwolf20.buildinggadgets.common.tools.ToolRenders$Utils.getSilkDropIfPresent(ToolRenders.java:565)
    at com.direwolf20.buildinggadgets.common.tools.ToolRenders$Utils.access$200(ToolRenders.java:523)
    at com.direwolf20.buildinggadgets.common.tools.ToolRenders.renderExchangerOverlay(ToolRenders.java:186)
    at com.direwolf20.buildinggadgets.client.proxy.ClientProxy.renderWorldLastEvent(ClientProxy.java:94)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_621_ClientProxy_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at farseek.world.gen.structure.package$.post(package.scala:38)
    at farseek.world.gen.structure.package.post(package.scala)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1432)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1259)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1062)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
`

- BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar  
- BuildingGadgets-2.7.4.jar

**Comment by MajorTuvok** [comment]
Again not a Building Gadgets issue: Ferdinands flower mod should use the blockstate passed to the function instead of querying it from the world.

**Comment by MichaelHillcox** [comment]
I'll see if I can resolve this with a try catch but for now it's down to the mods to handle blockstate correctly. You'll notice this doesn't happen with any blocks from MC.
