### ISSUE TITLE
[1.15.2] Crash on load

### ISSUE THREAD

**Issue by iarspider** [Direwolf20-MC/BuildingGadgets#469]
After deleting this template, please provide the following information:
* Forge version 31.1.43
* Building Gadgets version 3.3.4
* Full log: https://gist.github.com/iarspider/a2c7fc6986064a28b7d7d3c2e2cc6994
* How to reproduce the issue: Just 
* A screenshot, if applicable

**Comment by MichaelHillcox** [comment]
This crash is not ours: 
```
	at net.minecraft.client.renderer.color.BlockColors.func_186722_a(BlockColors.java:97)
	at net.blay09.mods.cookingforblockheads.client.TileEntityRenderers.initBlockColors(TileEntityRenderers.java:36)
```

Looks to be an issue with cooking for block heads mod

**Comment by iarspider** [comment]
@MichaelHillcox https://github.com/blay09/CookingForBlockheads/issues/419 . Your crash is higher up in the log: https://gist.github.com/iarspider/a2c7fc6986064a28b7d7d3c2e2cc6994#file-gistfile1-txt-L2316

**Comment by MichaelHillcox** [comment]
Could you try this one and see if you're still getting a crash? if you can, can you post the crashlog (found in the instance dir under the folder crashlog). https://s.mikey.pro/buildinggadgets-3.3.4.jar

**Comment by iarspider** [comment]
Nope, no crash this time.

**Comment by MichaelHillcox** [comment]
Awesome, I'll release that soon :+1:

**Comment by CarlosCS28** [comment]
Help me
![2020-05-06_10 42 03](https://user-images.githubusercontent.com/64914242/81198397-0a09e900-8f87-11ea-99e1-86673a36d2ca.png)

**Comment by MajorTuvok** [comment]
@CarlosCS28 why?
