### ISSUE TITLE
Copy/Paste Gadget Anchoring Eats All Available Memory

### ISSUE THREAD

**Issue by r-mc2** [Direwolf20-MC/BuildingGadgets#621]
#### Building Gadgets version
`buildinggadgets-1.16.5-3.8.0` (most recently used version this occurred on)

#### Forge version
v36.0.25

#### Do you have optifine installed?
No.

#### Modpack (with version), if applicable
Has occurred in both `Enigmatica 6 v0.3.x` & `TNP Limitless 3 v1.9.6`

#### If the issue is a crash; An external link to the crash report
I previously reported this on the [E6 tracker](https://github.com/NillerMedDild/Enigmatica6/issues/1172) and appropriate logs are also over there

**Logs**
<details>
<summary>Click to Show/Hide Logs</summary>
<pre>
[00:49:53] [Render thread/ERROR]: Exception caught during firing event: null
	Index: 11
	Listeners:
	...
	11: ASM: class com.direwolf20.buildinggadgets.client.events.EventRenderWorldLast renderWorldLastEvent(Lnet/minecraftforge/client/event/RenderWorldLastEvent;)V
	...

java.lang.OutOfMemoryError
	at sun.misc.Unsafe.allocateMemory(Native Method)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:127)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at net.minecraft.client.renderer.GLAllocation.func_74524_c(SourceFile:18)
	at com.direwolf20.buildinggadgets.client.renderer.DireBufferBuilder.<init>(DireBufferBuilder.java:45)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender$MultiVBORenderer.sort(CopyPasteRender.java:279)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender.renderTargets(CopyPasteRender.java:151)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender.lambda$null$1(CopyPasteRender.java:138)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender$$Lambda$31626/1527279985.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender.lambda$null$2(CopyPasteRender.java:122)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender$$Lambda$31624/804571671.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender.lambda$renderPaste$3(CopyPasteRender.java:120)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender$$Lambda$31623/659127197.accept(Unknown Source)
	at net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:161)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender.renderPaste(CopyPasteRender.java:120)
	at com.direwolf20.buildinggadgets.client.renders.CopyPasteRender.render(CopyPasteRender.java:67)
	at com.direwolf20.buildinggadgets.client.events.EventRenderWorldLast.renderWorldLastEvent(EventRenderWorldLast.java:26)
	at net.minecraftforge.eventbus.ASMEventHandler_650_EventRenderWorldLast_renderWorldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2563/2049858837.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:154)
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:609)
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:425)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/968383091.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
</pre>
</details>
(Only difference to mention from the above log and the recent one was BG's listener was registered at index "#14")

#### If it's copy paste gadget related, the actual template that is causing the issue would be appreciated.
It is, but it does not appear to be any particular template. Using some of the prepared templates within the E6 client instance for Astral multiblocks and Mekanism multiblocks.
A few of the templates in question, but not an exhaustive list as this has been happening for a couple months now and some are lost to my own memory:
* [Astral Ritual Pedestal](https://github.com/NillerMedDild/Enigmatica6/blob/master/building_gadgets_patterns/astral_sorcery/ritual_pedestal.txt)
* [Astral Ritual Collector Crystal](https://github.com/NillerMedDild/Enigmatica6/blob/master/building_gadgets_patterns/astral_sorcery/enhanced_celestial_collector_crystal.txt)
* [Mekanism Thermal Evap. Tower](https://github.com/NillerMedDild/Enigmatica6/blob/master/building_gadgets_patterns/mekanism/basic_thermal_evap_tower.txt)

#### How to reproduce the issue
Usually how it happens is:
* I load up the tool with a new paste
* Head out to where I want to build
* (Remember I forgot to unanchor the previous build)
* Unanchor the previous location
* Get the ghost render where I like
* Reanchor
* Then somewhere along the lines of bumping the render around and/or walking near it, or more recently just opening the menu to bump the position of the anchor triggers the OOM.

#### Anything else we should know?
I don't think it's related to the complexity of the render as it's happened with a few of the Astral multiblocks as well as some of the Mekanism ones, too. Nor do I think I am actually getting low on memory, as Java is want to do, as it can happen at different lengths of time that I've had the pack open. The most recent OOM was after having been in world for less than 45 minutes. Not exactly long enough for it to be a building memory leak.

Forgive me if this is a repeat issue, but a quick search of "memory" issues didn't show anything similar to this in existing open or closed issues.

**Comment by MajorTuvok** [comment]
I think I know where this is coming from and I've got a few ideas hoe to fix it, though I didn't have the time to do all the performance tests related to this (sorry I wanted to implement a performance fix which would have touched this in the winter break, but didn't get to running all the tests to show that the performance improvement **s** are actually effective). 

The relevant part here is that we're always allocating a constant sized render buffer, which might have to grow if there are too many vertices to render. Whilst I think this is almost unavoidable, BG grows the buffer again for each sort, keeping the previous allocated buffer+the copy soource+the new buffer in memory (as it needs to be copied). Not only does this cause a lot of unusued memory to be allocated and deallocated (which has a very substantial and measurable performance impact [somewhere along the lines of 2-3 times the average render time for the preliminary tests I did already]), but also that memory for the very large (grown) buffers has to be available.
A very simple way to reduce the impact would be to allocate a buffer of just the required size for sorting, if sorting can't be performed in-place, which would reduce the impact on both memory and time by an order-of-magnitude.

**Comment by MajorTuvok** [comment]
Btw. thanks for the very detailed description :)

**Comment by Meshwa428** [comment]
Any fixes? I am having the same issue. Your description goes above and beyond the head of a meathead like me 😅.

My game version is
1.16.5 forge - 36.2.34

And the modpack I use is

Mystical block 2.7.3

Issue:
Every time I take the copy paste gadget in my hand (Note: when I already have anchored a build) my game just crashes and shows OOM (Out of Memory error)
I have 7gb of ram allocated to the game and the copy-paste gadget eats it all 😭
